Algoritmo "2"

Var
v1 : vetor[0..5] de inteiro
v2 : vetor[0..5] de inteiro
v3 : vetor[0..5] de inteiro
contador : inteiro
Inicio
para contador de 1 ate 5 faca
ESCREVA("DIGITE O NUMERO PARA O VETOR1: ")
leia(v1[contador])
 ESCREVA("DIGITE O NUMERO PARA O VETOR2: ")
leia(v2[contador])
v3[contador] <- v1[contador] + v2[contador]
fimpara

para contador de 1 ate 5 faca
escreval("vet1 = ", v1[contador], " + vet2 = ", v2[contador]," = vet3 = ", v3[contador])
fimpara




Fimalgoritmo