Algoritmo "Covid"

Var
p1, p2, p3, p4, p5, p6, p7, p8, p9, p10 : real
 p11, p12, p13, p14, p15, p16, p17, p18, p19, p20 : real
 c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11 : real
 c12, c13, c14, c15, c16, c17, c18, c19, c20 : real
 m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11 : real
 m12, m13, m14, m15, m16, m17, m18, m19, m20 : real



Inicio
escreva("Digite o numero de mortes no Estados Unidos ")
leia(m1)
escreva("o numero de casos no pais é ")
leia(c1)
escreva("Digite o numero de mortes no Brasil ")
leia(m2)
escreva("o numero de casos no pais é ")
leia(c2)
escreva("Digite o numero de mortes no Índia ")
leia(m3)
escreva("o numero de casos no pais é ")
leia(c3)
escreva("Digite o numero de mortes no Rússia ")
leia(m4)
escreva("o numero de casos no pais é ")
leia(c4)
escreva("Digite o numero de mortes no África do Sul ")
leia(m5)
escreva("o numero de casos no pais é ")
leia(c5)
escreva("Digite o numero de mortes no México ")
leia(m6)
escreva("o numero de casos no pais é ")
leia(c6)
escreva("Digite o numero de mortes no Peru ")
leia(m7)
escreva("o numero de casos no pais é ")
leia(c7)
escreva("Digite o numero de mortes no Colômbia ")
leia(m8)
escreva("o numero de casos no pais é ")
leia(c8)
escreva("Digite o numero de mortes no Chile ")
leia(m9)
escreva("o numero de casos no pais é ")
leia(c9)
escreva("Digite o numero de mortes no Irã ")
leia(m10)
escreva("o numero de casos no pais é ")
leia(c10)
escreva("Digite o numero de mortes no Espanha ")
leia(m11)
escreva("o numero de casos no pais é ")
leia(c11)
escreva("Digite o numero de mortes no Reino Unido ")
leia(m12)
escreva("o numero de casos no pais é ")
leia(c12)
escreva("Digite o numero de mortes no Arábia Saudita ")
leia(m13)
escreva("o numero de casos no pais é ")
leia(c13)
escreva("Digite o numero de mortes no Paquistão ")
leia(m14)
escreva("o numero de casos no pais é ")
leia(c14)
escreva("Digite o numero de mortes no Bangladesh ")
leia(m15)
escreva("o numero de casos no pais é ")
leia(c15)
escreva("Digite o numero de mortes no Itália ")
leia(m16)
escreva("o numero de casos no pais é ")
leia(c16)
escreva("Digite o numero de mortes no Turquia ")
leia(m17)
escreva("o numero de casos no pais é ")
leia(c17)
escreva("Digite o numero de mortes no Alemanha ")
leia(m18)
escreva("o numero de casos no pais é ")
leia(c18)
escreva("Digite o numero de mortes no França ")
leia(m19)
escreva("o numero de casos no pais é ")
leia(c19)
//Realizando as operações

p1 <- c1 / m1
Escreval("No Estados Unidos, a cada ", p1," casos, tem uma morte")
p2 <- c2 / m2
Escreval("No Brasil , a cada ", p2," casos, tem uma morte")
p3 <- c3 / m3
Escreval("Na Índia , a cada ", p3," casos, tem uma morte")
p4 <- c4 / m4
Escreval("Na Rússia , a cada ", p4," casos, tem uma morte")
p5 <- c5 / m5
Escreval("Na África do Sul , a cada", p5," casos, tem uma morte")
p6 <- c6 / m6
Escreval("No México, a cada ", p6," casos, tem uma morte")
p7 <- c7 / m7
Escreval("No Peru, a cada ", p7," casos, tem uma morte")
p8 <- c8 / m8
Escreval("Na Colômbia, a cada ", p8," casos, tem uma morte")
p9 <- c9 / m9
Escreval("No Chile, a cada ", p9," casos, tem uma morte")
p10 <- c10 / m10
Escreval("No Irã, a cada ", p10," casos, tem uma morte")
p11 <- c11 / m11
Escreval("Na Espanha, a cada ", p11," casos, tem uma morte")
p12 <- c12 / m12
Escreval("No Reino Unido, a cada ", p12," casos, tem uma morte")
p13 <- c13 / m13
Escreval("Na Arábia, a cada ", p13," casos, tem uma morte")
p14 <- c14 / m14
Escreval("No Paquistão, a cada ", p14," casos, tem uma morte")
p15 <- c15 / m15
Escreval("No Bangladesh, a cada ", p15," casos, tem uma morte")
p16 <- c16 / m16
Escreval("Na Ítalia, a cada ", p16," casos, tem uma morte")
p17 <- c17 / m17
Escreval("Na Turquia, a cada ", p17," casos, tem uma morte")
p18 <- c18 / m18
Escreval("Na Alemanha, a cada ", p18," casos, tem uma morte")
p19 <- c19 / m19
//Dados para uso do programa
//Estados Unidos: Mortes - 165286 / casos - 5182177
//Brasil: Mortes - 101857 / casos -3057470
//Índia: Mortes - 45257/ casos -226875
//Rússia: Mortes - 15131/ casos -897599
//Africa do sul: Mortes - 10621/ casos -563598
//México: Mortes - 53003/ casos -485836
//Peru: Mortes - 21276/ casos -483133
//Colômbia: Mortes - 13154/ casos -397623
//Chile: Mortes - 10139/ casos - 375044
//Irã: Mortes -18800 / casos - 331189
//Espanha: Mortes - 28576/ casos -322980
//Reino Unido: Mortes - 46526/ casos -311641
//Arabia Saudita: Mortes - 3233/ casos -291468
//Paquistão: Mortes -6112 / casos -285191
//Bangladesh: Mortes - 3471/ casos -263503
//Itália: Mortes - 35209/ casos - 250825
//Turquia: Mortes - 5858/ casos -241997
//Alemanha: Mortes - 9265/ casos -218500
//França: Mortes - 30340/ casos -202775



Fimalgoritmo