Algoritmo "Exercicio 2"

Var
 numeroUm, numeroDois : inteiro


Inicio
      escreva("Digite o primeiro numero: ")
      leia(numeroUm)
      escreva("digite o segundo numero: ")
      leia(numeroDois)
      
      se(numeroUM < numeroDois) entao
           escreva("numeroDois é maior e numeroUm é o menor entre eles")
      senao
           escreva("numeroUm é maior e numeroDois é o menor entre eles")
      fimse

Fimalgoritmo