Algoritmo "fração"

Var
n1 : vetor [0..19] de inteiro
r1 : real
contador : inteiro

Inicio

para contador de 0 ate 19 faca
escreva("Numero: ")
leia(n1[contador])

fimpara

r1 <- n1[0] + n1[1] + n1[2] + n1[3] + n1[4] + n1[5] + n1[6] + n1[7] + n1[8] + n1[9] + n1[10] + n1[11] + n1[12] + n1[13] + n1[14] + n1[15] + n1[16] + n1[17] + n1[18] + n1[19]

escreva("O resultado deles somados é: ", r1)
Fimalgoritmo